language: python
python:
 - "3.6"

addons:
  apt:
    packages:
      - openjdk-8-jre  # install Java8 as required by vnu.jar

before_install:
        - gem install github-pages concurrent-ruby

install:
 - pip install html5validator

script: 
  - jekyll build --drafts --profile
  - html5validator --root _site/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# https://github.com/ebu/ebu-tt-live-toolkit/issues/139#issuecomment-324696334
# Build all branches, *including* gh-pages:
branches:
  only:
    - gh-pages
    - /.*/
